### ISSUE TITLE
Fails with NPM 5.5.1

### ISSUE THREAD

**Issue by freaktechnik** [ljharb/npm-deprecations#1]
On messages.js#15 the parse fails, because it gets an empty string. My quick fix locally was to add a `jsonMessage.length` check to the if one line earlier.

**Comment by ljharb** [comment]
Can you provide a package name this fails with?

**Comment by freaktechnik** [comment]
Just about any package where the version being tested is not deprecated. So for example `github-stub`, `transifex-config`, `transifex-loader`, `twitchbots-base`, `get-firefox` and many more.

I came across this when creating https://www.npmjs.com/package/my-deprecations, which is broken for me without modifying the messages.js.

As mentioned in the title I'm running NPM 5.5.1, to be exact the version that comes with node 9.

**Comment by ljharb** [comment]
I believe this is already fixed by 9dbfdf1bd79974206b602d5116a7225f1be54a76, but not yet released :-)

**Comment by freaktechnik** [comment]
That should have the same effect as my quick fix, yeah. Any idea when you'll release a version with the fix?

**Comment by ljharb** [comment]
v2.0.2 is released.

**Comment by freaktechnik** [comment]
verified fixed. Thanks 👍
